//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorsShedule
    {
        public int Id { get; set; }
        public System.TimeSpan BeginingDate { get; set; }
        public System.TimeSpan EndDate { get; set; }
        public int IdDoctor { get; set; }
    
        public virtual Doctors Doctors { get; set; }
    }
}
